# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_auto_20171109_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaching',
            name='semester',
            field=models.BooleanField(verbose_name='semester:'),
        ),
    ]
