# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_auto_20171110_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='username',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
