# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_auto_20171110_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaching',
            name='semester',
        ),
    ]
