# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-11 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0026_auto_20171110_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='Upload_Profile_Pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
