# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-12 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0027_about_us_upload_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='Upload_Profile_Pic',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='students',
            name='Student_category',
            field=models.CharField(choices=[('M.Tech. Students Ongoing', 'M.Tech. Students Ongoing'), ('M.Tech. Students Completed', 'M.Tech. Students Completed'), ('Ph.D. Students continuing', 'Ph.D. Students continuing'), ('Ph.D. Students Completed', 'Ph.D. Students Completed')], default='select', max_length=255),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='Partners',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
