# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0030_auto_20171115_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='Department',
            field=models.CharField(choices=[('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), (' Chemical Engineering', ' Chemical Engineering'), ('Chemistry', 'Chemistry'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Design', 'Design'), ('Humanity and Social Sciences', 'Humanity and Social Sciences'), (' Electronics and Electrical Engineering ', ' Electronics and Electrical Engineering '), ('Mathematics', 'Mathematics'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Physics', 'Physics')], default=None, max_length=200),
        ),
    ]
